





// Style the container class to center its content horizontally and give it some top margin for spacing.



// Implement a function, let's call it getRandomColor(), which generates a random color. You may use hexadecimal or RGB values.
// Add an event listener to the change-color-btn element. When clicked, the event listener should trigger a function that changes the background color of the color-box to a random color generated by the getRandomColor() function.
// Testing:
// Open your HTML file in a web browser.
// Click the "Change Color" button and observe the color of the box change dynamically.